
[[session]]
name = "Downloads ğŸ“¥"
path = "~/Downloads"
startup_command = "nautilus /home/thomas/Downloads/"

[[session]]
name = "Home ğŸ "
path = "~/"

[[session]]
name = "Google Drive ğŸ§©"
path = "~/mnt/GDrive/"
startup_command = "nautilus /home/thomas/mnt/GDrive/"


[[session]]
name = "tmux config âš™ï¸"
path = "~/.dotfiles/tmux/"
startup_command = "nvim .tmux.conf"
preview_command = "bat --color=always ~/.dotfiles/tmux/.tmux.conf"

[[session]]
name = "nvim config âš¡"
path = "~/.dotfiles/nvim/.config/nvim/lua/plugins/"
startup_command = "nvim ."
preview_command = "bat --color=always ~/.dotfiles/nvim/.config/nvim/init.lua"

[[session]]
name = "dotfilesğŸ”‘"
path = "~/.dotfiles"

[[session]]
name = "sesh config ğŸ“"
path = "~/.dotfiles/sesh/.config/sesh/"
startup_command = "nvim sesh.toml"
preview_command = "bat --language=toml --style=snip --color=always ~/.dotfiles/sesh/.config/sesh/sesh.toml"

[[session]]
name = "kitty config ğŸ±"
path = "~/.dotfiles/kitty/.config/kitty"
startup_command = "nvim kitty.conf"
preview_command = "bat --color=always ~/.dotfiles/kitty/.config/kitty/kitty.conf"

[[session]]
name = "i3 config ğŸ§±"
path = "~/.dotfiles/i3/.config/i3"
startup_command = "nvim config"
preview_command = "bat --color=always ~/.dotfiles/i3/.config/i3/config"

[[session]]
name = "zsh config ğŸš"
path = "~/.dotfiles/zsh"
startup_command = "nvim .zshrc"
preview_command = "bat --color=always ~/.dotfiles/zsh/.zshrc"
